<?php
$version = $this->config->get('version');
$pageAttr = $this->pageAttr ? $this->pageAttr : [];
$pageAttr['token'] = $this->token();
$pageAttr['now'] = micro_date();
$pageAttr['localeKey'] = 'zh-cn';
$pageAttr['qiniuDomain'] = $this->config->get('qiniu.domain');
$pageAttr['fetchUpToken'] = $this->routeGetRest('fetchUpToken');
$pageAttr['fromAccToken'] = $this->fromAccToken;
$pageAttr['toAccToken'] = $this->toAccToken;
?><!DOCTYPE html>
<html lang="<?php echo $this->request->getLocaleKey(); ?>" prefix="og: http://ogp.me/ns#">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?php echo $this->staticUrl('css/chat.css?v=' . $version); ?>">
    <title><?php echo $this->trans('ideapar'); ?></title>
    <?php $this->section('style'); ?><?php $this->stop(); ?>
</head>
<body class="chat-body">
<div class="layout-container">
    <div class="layout-main">
        <div class="header">
            <div>
                <i class="icon icon-logo-name"></i>
            </div>
            <div class="search-bar-wraper">
            </div>
        </div>
        <div class="body">
            <div class="menu-pannel">
                <div class="profile">
                    <div class="user-avatar big-52 with-border" style="background-image: url(<?php echo $this->profile->getAvatar(); ?>);">
                    </div>
                </div>
                <ul class="main-menus">
                    <li class="menu-item">
                        <i class="icon icon-chat"></i>
                    </li>
                    <li class="menu-item">
                        <i class="icon icon-contact"></i>
                    </li>
                </ul>
                <ul class="extra-options">
                </ul>
            </div>
            <div class="menu-pannel-body">
                <div class="sub-menu-pannel" class="contact-list-pannel">
                    <div class="contact-lists-box" id="user-lists">
                        <div class="contact-lists" id="contact-lists">
                            <div class="list-item contact-item context-menu contact-item-company" accToken="">
                                <i class="icon icon-close"></i>
                                <div class="avatar-wrap">
                                    <div class="user-avatar normal" style="background-image: url(&quot;https://static.dingtalk.com/media/lALOAFF1eczIzMg_200_200.png_60x60q90.jpg&quot;);"></div>
                                </div>
                                <div class="contact-item-content">
                                    <div class="title-wrap">
                                        <div class="name-wrap">
                                            <span>Jason</span>
                                        </div>
                                        <span class="time">10-12</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="content-pannel">
                    <div class="contact-detail-pannel">
                        <div class="nocontent-logo"></div>
                        <div class="content-pannel-head chat-head">
                            this is 
                        </div>
                        <div class="content-pannel-body chat-box-new" id="chat-box">
                            <div class="main-chat chat-items" id="chat-lists">

                            </div>
                        </div>
                        <div class="send-msg-box-wrapper">
								<div class="input-area" style="">
									<ul class="tool-bar">
										<li class="tool-item">
											<i class="icon icon-upload-file-chat" id="btn-upload" title="表情"></i>
											<div class="faceDiv"></div>
										</li>
									</ul>
									<span class="user-guide">Ctrl+Enter 发送, Enter 换行</span>
									<div class="msg-box" style="height:100%;">
										<textarea class="textarea input-msg-box" id="chat-text"></textarea>
									</div>
								</div>
								<div class="action-area" style="" id="send-button">
									<a href="javascript:;" class="send-message-button">发送</a>
								</div>
							</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="page-attr"
       value="<?php echo attr_json($pageAttr); ?>">

<script src="<?php echo $this->staticUrl('js/chat.js?v=' . $version); ?>"></script>
<?php $this->section('script'); ?><?php $this->stop(); ?>
</body>
</html>
