<?php
$this
    ->site('www')
    ->access('login')

    ->get(
        '/user',
        'fetchMassUser',
        'Openmessage\MassUser\User\Ui\FetchUserController@show'
    )
    ->postRest(
        '/api/set-name-of-user',
        'setNameOfUser',
        'Openmessage\MassUser\User\Rest\SetNameOfUserController@post'
    )
    ->postRest(
        '/api/set-avt-of-user',
        'setAvtOfUser',
        'Openmessage\MassUser\User\Rest\SetAvtOfUserController@post'
    )
    ->postRest(
        '/api/set-weixin-of-user',
        'setWeixinOfUser',
        'Openmessage\MassUser\User\Rest\SetWeixinOfUserController@post'
    )
    ->postRest(
        '/api/set-addr-of-user',
        'setAddrOfUser',
        'Openmessage\MassUser\User\Rest\SetAddrOfUserController@post'
    )
    ->postRest(
        '/api/add-addr-of-user',
        'addAddrOfUser',
        'Openmessage\MassUser\User\Rest\AddAddrOfUserController@post'
    )
    ->postRest(
        '/api/set-phone-of-user',
        'setPhoneOfUser',
        'Openmessage\MassUser\User\Rest\SetPhoneOfUserController@post'
    )
    ->postRest(
        '/api/set-email-of-user',
        'setEmailOfUser',
        'Openmessage\MassUser\User\Rest\SetEmailOfUserController@post'
    )
    ->get(
        '/set-wx-and-name-of-user',
        'setWxAndNameOfUser',
        'Openmessage\MassUser\User\Ui\SetNameAndWxForUserController@show'
    )
    ->post(
        '/set-wx-and-name-of-user',
        'setWxAndNameOfUser',
        'Openmessage\MassUser\User\Ui\SetNameAndWxForUserController@post'
    );
