<?php
$this
    ->access('public')
    ->site('www')

    ->get(
        '/reg/email',
        'regByEmail',
        'Openmessage\Auth\Reg\Ui\RegByEmailController@show'
    )
    ->post(
        '/reg/email',
        'regByEmail',
        'Openmessage\Auth\Reg\Ui\RegByEmailController@post'
    )
    ->get(
        '/reg/email-success',
        'regSuccessByEmail',
        'Openmessage\Auth\Reg\Ui\RegByEmailController@success'
    )
    ->get(
        '/reg/phone',
        'regByPhone',
        'Openmessage\Auth\Reg\Ui\RegByPhoneController@show'
    )
    ->post(
        '/reg/phone',
        'regByPhone',
        'Openmessage\Auth\Reg\Ui\RegByPhoneController@post'
    )
    ->get(
        '/reg/phone-success',
        'regSuccessByPhone',
        'Openmessage\Auth\Reg\Ui\RegByPhoneController@success'
    )
    ->postRest(
        '/email/send-verify-code',
        'sendVerifyCodeByEmail',
        'Openmessage\Auth\Reg\Rest\SendVerifyCodeByEmail@post'
    )
    ->postRest(
        '/phone/send-verify-code',
        'sendVerifyCodeByPhone',
        'Openmessage\Auth\Reg\Rest\SendVerifyCodeByPhone@post'
    )
    ->postRest(
        '/verify-code-by-email',
        'checkVerifyCodeByEmail',
        'Openmessage\Auth\Reg\Rest\CheckVerifyCodeByEmail@post'
    )
    ->postRest(
        '/verify-code-by-phone',
        'checkVerifyCodeByPhone',
        'Openmessage\Auth\Reg\Rest\CheckVerifyCodeByPhone@post'
    )
    ->get(
        '/reg-agreement',
        'fetchAgreement',
        'Openmessage\Auth\Reg\Ui\FetchAgreementController@show'
    );
