<?php
$this->layout('layout/msg-main', [
    'pageAttr' => [
    ],
]);
?>

<?php $this->section('main'); ?>
    <section class="main">
    <div class="container">
        <div class="card">
            <div class="card-title">
                <?php echo $this->trans('createApp')?>
            </div>
            <div class="card-content">
                <form method="POST" action="<?php echo $this->routePost('createApp'); ?>">
                    <input type="hidden" name="token" value=<?php echo $this->token();?>>
                    <div class="item">
                        <label for="name"><?php echo $this->trans('name')?></label>
                        <input type="text" name="name">
                    </div>
                    <div class="item">
                        <label for="desc"><?php echo $this->trans('desc')?></label>
                        <input type="text" name="desc">
                    </div>
                    <div class="item">
                        <button class="btn submit float-right"><?php echo $this->trans('submit'); ?></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </section>
<?php $this->replace(); ?>

