<?php
$this->layout('layout/openmessage-main', [
    'pageAttr' => [

    ],
]);
$user = $this->user;
?>
<?php $this->section('main'); ?>
    <section class="main">
        <div class="set-wechat-wrap">
            <div class="card m-t-lg">
                <form action="<?php echo $this->routePost('setWxAndNameOfUser'); ?>" method="post">
                    <input type="hidden" name="token" value="<?php echo $this->token(); ?>">
                    <h2 class="form-title title large border-b"><?php echo $this->trans('setWxAndNameOfUser'); ?></h2>
                    <div class="form-content">
                        <div class="meta-item">
                            <div class="key"><span><?php echo $this->trans('name'); ?></span></div>
                            <div class="value">
                                <div class="name-info">
                                    <input type="text" name="nick" required value="<?php echo $user->getNick(); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="meta-item">
                            <div class="key"><span><?php echo $this->trans('weixin'); ?></span></div>
                            <div class="value">
                                <div class="weixin-info">
                                    <input type="text" name="weixin" required value="<?php echo $user->getWeixin(); ?>">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-footer text-center">
                        <input class="btn primary" type="submit" value="<?php echo $this->trans('submit'); ?>">
                    </div>
                </form>
            </div>
        </div>
    </section>

<?php $this->replace(); ?>
