<?php
$this->layout('layout/openmessage-proofer', [
    'pageAttr' => [
        'fetchUpToken' => $this->routeGetRest('fetchUpToken'),
        'setProofer' => $this->routePostRest('setProofer'),
    ],
]);
$user = $this->user;
$proofer = $this->proofer;
?>
<?php $this->section('main'); ?>
    <section class="main">
        <div class="set-proofer-wrap loader" zon-load="user.load" data-page="user/setProofer">
            <div class="card">
                <form action="javascript:;" method="post">
                    <input type="hidden" name="token" value="<?php echo $this->token(); ?>">
                    <h2 class="form-title title large border-b"><?php echo $this->trans('setProofer'); ?></h2>
                    <div class="form-content">
                        <div class="meta-item">
                            <div class="key"><span><?php echo $this->trans('name'); ?></span></div>
                            <div class="value">
                                <div class="name-info">
                                    <input type="text" name="name" required value="<?php echo $proofer->getName(); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="meta-item">
                            <div class="key"><span><?php echo $this->trans('weixin'); ?></span></div>
                            <div class="value">
                                <div class="weixin-info">
                                    <input type="text" name="weixin" required value="<?php echo $user->getWeixin(); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="meta-item">
                            <div class="key"><span><?php echo $this->trans('company'); ?></span></div>
                            <div class="value">
                                <div class="company-info">
                                    <input type="text" name="company" required value="<?php echo $proofer->getCompany(); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="meta-item">
                            <div class="key"><span><?php echo $this->trans('companyAddr'); ?></span></div>
                            <div class="value">
                                <div class="addr-info">
                                    <input type="text" name="addr" required value="<?php echo $proofer->getAddr(); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="meta-item">
                            <div class="key"><span><?php echo $this->trans('business'); ?></span></div>
                            <div class="value">
                                <div class="business-info">
                                    <input type="text" name="business" required value="<?php echo $proofer->getBusiness(); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="meta-item">
                            <div class="key"><span><?php echo $this->trans('equip'); ?></span></div>
                            <div class="value">
                                <div class="equip-info">
                                    <input type="text" name="equip" required value="<?php echo $proofer->getEquip(); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="meta-item">
                            <div class="key"><span><?php echo $this->trans('position'); ?></span></div>
                            <div class="value">
                                <div class="position-info">
                                    <input type="text" name="position" required value="<?php echo $proofer->getPosition(); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="meta-item">
                            <div class="key"><span><?php echo $this->trans('phone'); ?></span></div>
                            <div class="value">
                                <div class="phone-info">
                                    <input type="text" name="phone" required value="<?php echo $proofer->getPhone(); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="meta-item">
                            <div class="key"><span><?php echo $this->trans('email'); ?></span></div>
                            <div class="value">
                                <div class="email-info">
                                    <input type="text" name="email" required value="<?php echo $proofer->getEmail(); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="meta-item">
                            <div class="key"><span><?php echo $this->trans('licence'); ?></span></div>
                            <div class="value">
                                <div class="licence-info">
                                    <input type="hidden" name="licenceBefore" value='<?php echo $proofer->getLicence(); ?>'>
                                    <input type="hidden" name="licence" value=''>
                                    <?php
                                        $qiniuDomain = $this->config->get('qiniu.domain');
                                        $qiniuThumb = '?imageMogr2/thumbnail/500x/strip/quality/50/format/jpg';
                                    ?>
                                    <?php if ($proofer->getLicence() != '' && $proofer->getLicence() != '[]') { ?>
                                        <img src="<?php echo $qiniuDomain . json_decode($proofer->getLicence(), true)[0] . $qiniuThumb; ?>">
                                    <?php }?>
                                    <div class="upload-img"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-footer text-center">
                        <input class="btn primary" type="submit" value="<?php echo $this->trans('submit'); ?>">
                    </div>
                </form>
            </div>
        </div>
    </section>

<?php $this->replace(); ?>
