<?php
$this->layout('layout/msg-main', [
    'pageAttr' => [
    ],
]);
?>

<?php $this->section('main'); ?>
    <section class="main">
    <div class="container">
        <div class="card">
            <div class="card-title">
                <?php echo $this->trans('createPush')?>
            </div>
            <div class="card-content">
                <form method="POST" action="/open/createPush">
                    <input type="hidden" name="createdUser" value="user">
                    <input type="hidden" name="key" value="<?php echo $this->app->getKey();?>">
                    <input type="hidden" name="secret" value="<?php echo $this->app->getSecret();?>">
                    <div class="item">
                        <label for="title"><?php echo $this->trans('title')?></label>
                        <input type="text" name="title">
                    </div>
                    <div class="item">
                        <label for="content"><?php echo $this->trans('content')?></label>
                        <input type="text" name="content">
                    </div>
                    <div class="item">
                        <label for="props"><?php echo $this->trans('props')?></label>
                        <input type="text" name="props">
                    </div>
                    <div class="item">
                        <label for="toAccIds"><?php echo $this->trans('toAccIds')?></label>
                        <input type="text" name="toAccId">
                    </div>
                    <div class="item">
                        <label for="toGroupIds"><?php echo $this->trans('toGroupIds')?></label>
                        <input type="text" name="toGroupId">
                    </div>
                    <div class="item">
                        <button class="btn submit float-right"><?php echo $this->trans('submit'); ?></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </section>
<?php $this->replace(); ?>

